version: "3.8"

services:
  app:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - POETRY_VIRTUALENVS_CREATE=false
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    depends_on:
      - db

  # Optional, if you have a database service
  db:
    image: postgres:13
    container_name: fastapi-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
