name: CI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --cache-from=type=gha --cache-to=type=gha,mode=max -t fastapi-app .

      - name: Run Unit Tests inside Docker with coverage
        run: |
          docker run --rm \
            -e PYTHONPATH=/app \
            -v ${{ github.workspace }}/coverage:/app/coverage \
            fastapi-app poetry run pytest --cov=app --cov-report=xml:/app/coverage/coverage.xml --cov-report=html:/app/coverage/html tests/test_unit.py

      - name: Upload Coverage Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage-report
          path: coverage/

  acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --cache-from=type=gha --cache-to=type=gha,mode=max -t fastapi-app .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name fastapi-container fastapi-app

      - name: Wait for container to be ready
        run: |
          until curl -s http://localhost:8000/docs; do
            echo "Waiting for FastAPI to start..."
            sleep 5
          done

      - name: Run Acceptance Tests with Coverage
        run: |
          docker run --rm --network host -e PYTHONPATH=/app -v ${{ github.workspace }}/coverage:/app/coverage fastapi-app poetry run pytest --cov=app --cov-report=xml:/app/coverage/coverage-acceptance.xml --cov-report=html:/app/coverage/html tests/test_acceptance.py

      - name: Upload Acceptance Test Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-test-coverage-report
          path: coverage/

  sonarqube-analysis:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest
    needs: [unit-tests, acceptance-tests]

    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for SonarQube to be ready
        run: |
          timeout=300  # 5 minutes timeout
          interval=10  # Check every 10 seconds
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if curl -s http://localhost:9000/api/system/status | grep -q "UP"; then
              echo "SonarQube is ready!"
              break
            fi
            echo "Waiting for SonarQube to be ready... ($elapsed/$timeout seconds elapsed)"
            sleep $interval
            elapsed=$((elapsed + interval))
          done

          if [ $elapsed -ge $timeout ]; then
            echo "SonarQube did not become ready in time!" >&2
            exit 1
          fi

      - name: Run SonarQube Scanner
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/usr/src \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.sources=./app \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=admin \
            -Dsonar.password=admin \
            -Dsonar.qualitygate.wait=true

      - name: Upload SonarQube Analysis Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-analysis-report
          path: path/to/sonar-report.json  # Or .xml, depending on the report format
