name: CI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Run Unit Tests inside Docker
        env:
          PYTHONPATH: /app  # Set PYTHONPATH as environment variable
        run: docker run --rm --network host -e PYTHONPATH=/app fastapi-app poetry run pytest tests/test_unit.py

  acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name fastapi-container fastapi-app

      - name: Wait for container to be ready
        run: |
          until curl -s http://localhost:8000/docs; do
            echo "Waiting for FastAPI to start..."
            sleep 5
          done

      - name: Run Acceptance Tests
        env:
          PYTHONPATH: /app  # Set PYTHONPATH as environment variable
        run: docker run --rm --network host -e PYTHONPATH=/app fastapi-app poetry run pytest tests/test_acceptance.py

