name: CI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Run Unit Tests with Coverage
        run: |
          mkdir -p coverage/  # Create a directory on the host for coverage files
          docker run --rm --network host -v ${{ github.workspace }}/coverage:/app/coverage fastapi-app poetry run pytest --cov=app --cov-report=xml:/app/coverage/coverage-unit.xml --cov-report=html:/app/coverage/html tests/test_unit.py

      - name: Upload Unit Test Coverage Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage-report
          path: coverage/  # Upload the entire coverage directory

  acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest
    needs: unit-tests  # This ensures that unit-tests must finish before acceptance-tests starts
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name fastapi-container fastapi-app

      - name: Wait for FastAPI to be ready
        run: |
          until curl -s http://localhost:8000/docs; do
            echo "Waiting for FastAPI to start..."
            sleep 5
          done

      - name: Download Unit Test Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: unit-test-coverage-report  # Ensure the artifact name matches exactly
          path: coverage/  # Download to coverage/ directory

      - name: Run Acceptance Tests with Coverage
        run: |
          mkdir -p coverage/  # Create a directory on the host for coverage files
          docker run --rm --network host -v ${{ github.workspace }}/coverage:/app/coverage fastapi-app poetry run pytest --cov=app --cov-report=xml:/app/coverage/coverage-acceptance.xml --cov-report=html:/app/coverage/html tests/test_acceptance.py

      - name: Combine Coverage Reports
        run: |
          docker run --rm -v ${{ github.workspace }}/coverage:/app/coverage fastapi-app poetry run coverage combine /app/coverage

      - name: Upload Combined Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage.xml
          flags: merged-coverage
          name: merged-coverage-report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish Combined Coverage Report as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: merged-coverage-report
          path: coverage/html/

      - name: Tear Down Docker Container
        run: docker stop fastapi-container && docker rm fastapi-container