# Basic workflow to run acceptance tests on push to master
name: Run Tests

# Run event: on push to master or opening a pr to master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        run: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run unit tests
        env:
          PYTHONPATH: .
        run: poetry run pytest tests/test_unit.py

    acceptance-tests:
      name: Run Acceptance Tests
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install

        - name: Run acceptance tests
          env:
            PYTHONPATH: .
          run: |
            poetry run pytest tests/test_acceptance.py
