name: CI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image with cache
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: fastapi-app
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-app-image
          path: fastapi-app.tar.gz
        run: |
          docker save fastapi-app | gzip > fastapi-app.tar.gz

      - name: Run Unit Tests inside Docker with coverage
        run: |
          docker run --rm \
            -e PYTHONPATH=/app \
            -v ${{ github.workspace }}/coverage:/app/coverage \
            fastapi-app poetry run pytest --cov=app --cov-report=xml:/app/coverage/coverage.xml --cov-report=html:/app/coverage/html tests/test_unit.py

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: /app/coverage/coverage.xml  # Path to coverage report
          flags: unittests  # Optional flag to label this report in Codecov
          name: codecov-coverage-report  # Name for the Codecov report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # Set the token in GitHub Secrets

      - name: Publish Coverage Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage/html/  # Upload the entire HTML coverage report

  acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: fastapi-app-image

      - name: Load Docker image from artifact
        run: docker load -i fastapi-app.tar.gz

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name fastapi-container fastapi-app

      - name: Wait for container to be ready
        run: |
          until curl -s http://localhost:8000/docs; do
            echo "Waiting for FastAPI to start..."
            sleep 5
          done

      - name: Run Acceptance Tests with Coverage
        run: |
          docker run --rm --network host -e PYTHONPATH=/app -v ${{ github.workspace }}/coverage:/app/coverage fastapi-app poetry run pytest --cov=app --cov-report=xml:/app/coverage/coverage-acceptance.xml --cov-report=html:/app/coverage/html tests/test_acceptance.py

      - name: Upload Acceptance Test Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-test-coverage-report
          path: coverage/

      - name: Upload Acceptance Test Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-acceptance.xml
          flags: acceptancetests
          name: acceptance-test-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Tear Down Docker Container
        run: docker stop fastapi-container && docker rm fastapi-container
